#!/bin/bash


# Set decoration geometry
berryc border_width       5
berryc inner_border_width 3
berryc title_height       30
berryc top_gap            30

# Set decoration colors
berryc focus_color         000000
berryc unfocus_color       000000
berryc inner_focus_color   000A20
berryc inner_unfocus_color 070416
berryc text_focus_color    EEF4ED
berryc text_unfocus_color  888098

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "false"
berryc set_font    "Dina-9"
