theme = "base16_transparent"
[editor]
mouse = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar" 
normal = "bar"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"